tribe365_live_web/routes/web.php
	Route::post('organisation-update4','Admin\AdminOrganisationController@organisation_update4')->name('organisation-update4');	
	/*Inactive organisation*/
	Route::post('organisation-delete','Admin\AdminOrganisationController@deleteOrganisation');
	/*delete organisation*/
	Route::post('delete-oragnisation','Admin\AdminOrganisationController@deleteWholeOrganisation');
	
	/*DOT FUNCTIONALITY*/	

	Route::resource('admin-dot','Admin\AdminDotController');
	/*show add page of custom adding page*/
	Route::get('custome-value','Admin\AdminDotController@createCustomValues')->name('custome-value');
	/*store custom value*/
	Route::post('store-custom-value','Admin\AdminDotController@storeCustomValues')->name('store-custom-value');
	/*get edit page of DOT*/
	Route::resource('dot-edit','Admin\AdminDotController');
	/*add DOT*/
	Route::get('dot-create/{id}','Admin\AdminDotController@addDot');
	/*UPDATE DOT*/
	Route::post('dot-update','Admin\AdminDotController@updateDotDetail')->name('dot-update');
	/*delete dot*/
	Route::post('dot-value-delete','Admin\AdminDotController@deleteDot');
	/* delete belief */
	Route::post('dot-belief-delete','Admin\AdminDotController@deleteBelief');
	/*UPDATE belief*/
	Route::post('dot-belief-update','Admin\AdminDotController@updateDotBeliefDetail')->name('dot-belief-update');
	/*ADD belief in edit section*/
	Route::post('dot-add-belief','Admin\AdminDotController@addBelief')->name('dot-add-belief');
	/*show add page of custom adding page*/
	Route::get('custome-value','Admin\AdminDotController@createCustomValues')->name('custome-value');
	/*store custom value*/
	Route::post('store-custom-value','Admin\AdminDotController@storeCustomValues')->name('store-custom-value');
	/*get custom values list*/
	Route::get('dot-custom-values','Admin\AdminDotController@beliefCustomeValues')->name('dot-custom-values');
	/*edit custom DOT value*/
	Route::get('edit-custom-value/{id}','Admin\AdminDotController@editCustomValue')->name('edit-custom-value');
	/*update dot custom values*/
	Route::post('update-custom-value','Admin\AdminDotController@updateCustomValues')->name('update-custom-value');
	/*delet dot custom values*/
	Route::get('delete-custom-value/{id}','Admin\AdminDotController@deleteCustomValue')->name('delete-custom-value');
	/*get evidence list*/ 
	Route::get('get-evidence-list/{dotId}/{type}/{id}','Admin\AdminDotController@getEvidenceList')->name('get-evidence-list');
	/*get custom dot values modal */
	Route::post('get-custom-value-evidence-modal','Admin\AdminDotController@getDotCustomValueList')->name('get-custom-value-evidence-modal');




	/*USER FUNCTIONALITY*/

	Route::resource('admin-user','Admin\AdminUserController');	

	Route::get('add-staff/{id}','Admin\AdminUserController@addStaff');
	/*get user /staff list*/
	Route::get('view-staff/{id}','Admin\AdminUserController@viewStaffList');
	/*add user by csv file*/
	Route::post('add-user-csv','Admin\AdminUserController@addUserCSV')->name('add-user-csv');
	/*export user list csv*/
	Route::get('user-list-export/{id}','Admin\AdminUserController@exportUserList');
	// delete user
	Route::post('delete-user','Admin\AdminUserController@destroy');


	/*ORGANISATION FUNCTIONALITY*/

	/*get organisation detail DOT COT org. SOT etc*/
	Route::get('organisation-detail/{id}','Admin\AdminOrganisationController@showOrganisationDetail');	
	/*get department create page */
	Route::get('add-office/{id}','Admin\AdminOrganisationController@addOffice');

	Route::get('list-office/{id}','Admin\AdminOrganisationController@listOffice');
	
	Route::post('create-office','Admin\AdminOrganisationController@createOffice');

	/*DEPARTMENT FUNCTIONALITY*/

	/*get all departments list*/
	Route::resource('departments','Admin\AdminDepartmentController');
	
	
	/*ACTION FUNCTIONALITY*/

	/*Dot action lits*/
	Route::get('action-list/{id}/{index?}/{feedthemeId?}','Admin\AdminActionController@getActionList');
	// Route::get('action-list/{id}','Admin\AdminActionController@getActionList');
	/*add DOT action */
	Route::get('add-action/{id}','Admin\AdminActionController@addAction');
	/*store active detail*/
	Route::resource('action','Admin\AdminActionController');
	/*get actions comments*/
	Route::get('action-comments/{id}','Admin\AdminActionController@getCommentsList');
	/*add new comments*/
	Route::post('action-add-comment','Admin\AdminActionController@addComment');
	/*updated actione status*/
	Route::post('action-status-update','Admin\AdminActionController@updateActionStatus');
	/*get responsible user list*/
	Route::POST('get-responsible-users','Admin\AdminActionController@getResUser');
	/*delete action*/
	Route::get('delete-action/{id}','Admin\AdminActionController@deleteAction');
	/*get action theme modal response */
	Route::post('get-action-theme-modal','Admin\AdminActionController@getActionThemeModal')->name('get-action-theme-modal');
	/*add new action theme by ajax when modal is open*/
	Route::post('add-new-action-theme-by-ajax','Admin\AdminActionController@addNewActionThemeByAjax')->name('add-new-action-theme-by-ajax');

	

	/*COMMON FUNCTIONALITY*/

	/*DEPARTMENT functionality*/
	Route::post('admin-add-department','Admin\CommonController@addNewDepartment')->name('admin-add-department');
	/*Common controller*/
	Route::get('get-department','Admin\CommonController@getAllDepartments');	
	/*get dot custom values list*/
	Route::get('get-custom-dot-list','Admin\CommonController@getCustomDotValues');
	/*check email is exists in table*/
	Route::post('search-email','Admin\CommonController@getEmail');	
	/*get offices list*/
	Route::post('get-offices','Admin\CommonController@getOfficeList');
	/*get departments list*/
	Route::post('get-department','Admin\CommonController@getDepartmentList');
	/*get user list*/
	Route::post('get-users','Admin\CommonController@getUsers');

	Route::get('inArray','Admin\CommonController@inArray');
	/*get org name*/
	Route::post('get-org-name','Admin\CommonController@getOrgName')->name('get-org-name');
	/*get search data of the values */
	Route::get('search-dot-values','Admin\CommonController@getDotValueSearchData')->name('search-dot-values');
	// /*send notification mail */
	Route::get('sendNotificationMail','Admin\CommonController@sendNotificationMail')->name('sendNotificationMail');
	/*get offices by organisation*/
	Route::post('getOfficesByOrgId','Admin\CommonController@getOfficesByOrgId');	
	/*get departments by office*/
	Route::post('getDepartmentByOfficecId','Admin\CommonController@getDepartmentByOfficecId');
	/*search organisation functionality in list organisation*/
	Route::post('searchOrganisations','Admin\CommonController@searchOrganisations');
	/*get office search result list*/
	Route::post('searchOffice','Admin\CommonController@searchOffice');
	/*get office search result list*/
	Route::post('searchStaff','Admin\CommonController@searchStaff');
	/*get departments search result list*/
	Route::post('searchDepartment','Admin\CommonController@searchDepartment'); 
	/*get search reports organisation result list*/
	Route::post('searchReportOrganisations','Admin\CommonController@searchReportOrganisations');
	/*get department by office id this is used in report graph section*/
	Route::post('getDepartmentByOfficecIdforGraph','Admin\CommonController@getDepartmentByOfficecIdforGraph');
	/*get office by organisation id this is used in dashboard graph section*/
	Route::post('getOfficeByOrgIdforGraph','Admin\CommonController@getOfficeByOrgIdforGraph');
	/*get department by office id in kudos leaderboard*/
	Route::post('getDepartmentByOfficecIdforKudos','Admin\CommonController@getDepartmentByOfficecIdforKudos');
	/*get office by organisation id in kudos leaderboard*/
	Route::post('getOfficeByOrgIdforKudos','Admin\CommonController@getOfficeByOrgIdforKudos');


	/*COT QUESTIONS FUNCTIONALITY*/

	Route::resource('cot-question','Admin\AdminCOTquestionController');
	/*get functional lens question list*/
	Route::get('cot-fun-questions','Admin\AdminCOTquestionController@getCOTfunctionalLensQuestionList');
	/*get cot functional lens questions option list*/
	Route::get('cot-fun-que-option/{id}','Admin\AdminCOTquestionController@getCOTfunctionalLensQuestionOptionList');
	/*update functional lens question and option*/
	Route::post('update-cot-fun-que-opt','Admin\AdminCOTquestionController@updateFunctionalLensQueOpt');


	
	/*COT FUNCTIONALITY*/

	Route::resource('cot','Admin\AdminCOTController');

	/*get cot detail page*/
	Route::get('cot-detail/{id}','Admin\AdminCOTController@getCotDetail');

	/*get team role map view*/
	Route::match(['get', 'post'],'cot-team-role-map/{id}','Admin\AdminCOTController@getTeamRoleMap');
	/*update organisaton has_cot status*/
	Route::get('cot-team-role-map-update-has-cot/{id}','Admin\AdminCOTController@updateCOTstatus');
	/*get COt maper rank DATA FROM API*/
	Route::get('getCOTmaperkey','API\ApiCOTController@getCOTmaperkey');
	/*get list of functional lens list*/
	Route::match(['get', 'post'],'cot-functional-lens/{id}','Admin\AdminCOTController@getFunctinalLensList');
	/*get functional lens manage page */
	Route::get('manual-functional-lens-detail','Admin\AdminCOTController@manageFunctionalLensList');
	/*update cot functional initial values*/
	Route::post('update-cot-fun-initial-value','Admin\AdminCOTController@updateCOTinitiatialValue');
	/*update cot functional insight values*/
	Route::post('update-cot-fun-strength-value','Admin\AdminCOTController@updateCOTfunctionalLensInsightForStrenghtValue');
	//edit page of COT functional lens tribe tips seek and persuade values
	Route::get('edit-cot-fun-tribe-tips-value/{id}/{type}','Admin\AdminCOTController@editCOTfunTribeTipsSeekPersuadeValues');
	/*update cot functional lens tribe tips seek and persuade values*/
	Route::post('update-cot-fun-tribe-tips-value','Admin\AdminCOTController@updateCOTtribeSeekPersuadevalues');
	/*delete cot functional lense tribe tips value */
	Route::get('delete-cot-fun-tribe-tips-value/{id}','Admin\AdminCOTController@deleteCOTfunLensTribeTipsvalue');

tribe365_live_web/resources/views/admin/department/addDepartment.blade.php
<!-- header -->
@section('title', 'Add Department')
@include('layouts.adminHeader')
<main class="main-content">
	<div class="add-fild-section">
		<div class="container">
			<div class="dot-section">
				<h2> Department </h2>
				<div class="form-section">

					<form id="form" action="{!!route('departments.store')!!}" method="post">
						{{csrf_field()}}
						
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">									
									<input type="text" name="department" placeholder="Enter Department" maxlength="100">
								</div>

								<div class="error" style="color:red;">
									{{$errors->first()}}
									{{session('message')}}
								</div>

							</div>

							<div class="Create-btn-cont">
								<button type="submit" class="btn">Add</button>
							</div>
						</div>
						
					</form>

				</div>
			</div>
		</div>
	</div>
</main>

@include('layouts.adminFooter')

tribe365_live_web/resources/views/admin/department/editDepartment.blade.php
<!-- header -->
@section('title', 'Edit Department')
@include('layouts.adminHeader')
<main class="main-content">
	<div class="add-fild-section">
		<div class="container">
			<div class="dot-section">
				<h2> Edit Department </h2>
				<div class="form-section">

					{{ Form::model($departments, ['method' => 'PUT', 'route' => array('departments.update', base64_encode($departments->id)),'id'=>'form','enctype'=>'multipart/form-data']) }}
					
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">									
								<input type="text" name="department" placeholder="Enter Department" value="{{$departments->department}}" maxlength="100">
							</div>

							<div class="error" style="color:red;">
								{{$errors->first()}}
								{{session('message')}}
							</div>

						</div>

						<div class="Create-btn-cont">
							<button type="submit" class="btn">Save</button>
						</div>
					</div>

				</form>

			</div>
		</div>
	</div>
</div>
</main>

@include('layouts.adminFooter')

tribe365_live_web/resources/views/admin/department/getCustomDepartments.blade.php
<!-- header -->
@section('title', 'List Department')
@include('layouts.adminHeader')
<main class="main-content">
	<div class="add-fild-section">
		<div class="container">
			<div class="ragistration-section">
				<div class="row">
					<div class="col-md-12">
						<div class="loader-img" style="display: none;width: 70px; top: -57px;"><img src="{{asset('public/images/loader.gif')}}"></div>
						<div class="search-section" style="width: 80%;">
							<form>
								<input id="search-key" type="search" placeholder="Search...">
							</form>                        
							<div align="center">                            
								@if(session('message'))
								<div class="alert alert-success" role="alert">                                    
									{{session('message')}}
								</div>
								@endif
							</div>                        
						</div>
						<h2> Departments </h2>
						<div class="adit-btn">
							<a href="{!!route('departments.create')!!}"><button class="savebtn" type="button" > Add </button></a>
						</div>
						<div class="value-list">
							<table class="search-sec">
								<tr> 
									<th> Name </th>									
								</tr>
								@foreach($departments as $value)
								<tr>								
									<td>
										{{ucfirst($value->department)}}<div class="editable">

											<a href="{!!route('departments.edit',['id'=>base64_encode($value->id)])!!}">
												<button type="button"><i class="fa fa-pencil" aria-hidden="true"></i></button>
											</a>

											{{ Form::open(['method'  => 'delete', 'route' => [ 'departments.destroy', base64_encode($value->id) ] ]) }}

											{{ Form::button('', ['type'=>'submit','onclick'=>'return confirm("Are you sure you want to delete ?")']) }}

											{{ Form::close() }}
										</div>
									</td>
									
								</tr>
								@endforeach()
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="organ-page-nav">
			{!! $departments->links('layouts.pagination') !!}
		</div>
	</div>
</main>

<script type="text/javascript">
	$(document).ready(function(){
		$("#search-key").keyup(function(){
			$('.search-sec').html('');			
			$('.organ-page-nav').html('');
			$('.loader-img').show();

			var department = $('#search-key').val();
			if(department==''){
				location.reload();
			}
			$.ajax({
				type: "POST",
				url: "{!!URL::to('admin/searchDepartment')!!}",             
				data: {department:department,"_token":'<?php echo csrf_token()?>'},
				success: function(response) {
					
					if(response.length > 1){

						$('.search-sec').html('');				
						$('.search-sec').append(response);             
						$('.loader-img').hide();
					}else{
						
						$('.search-sec').html('');
						$('.value-list').html('');				
						$('.value-list').append('<div align="center" class="text-danger" role="alert">No result found.</div>');
						$('.loader-img').hide();
					}
				}
			}); 		
		});
	});
</script>
@include('layouts.adminFooter')