tribe365_live_web/routes/web.php
	Route::resource('admin-dot','Admin\AdminDotController');
	/*show add page of custom adding page*/
	Route::get('custome-value','Admin\AdminDotController@createCustomValues')->name('custome-value');
	/*store custom value*/
	Route::post('store-custom-value','Admin\AdminDotController@storeCustomValues')->name('store-custom-value');
	/*get edit page of DOT*/
	Route::resource('dot-edit','Admin\AdminDotController');
	/*add DOT*/
	Route::get('dot-create/{id}','Admin\AdminDotController@addDot');
	/*UPDATE DOT*/
	Route::post('dot-update','Admin\AdminDotController@updateDotDetail')->name('dot-update');
	/*delete dot*/
	Route::post('dot-value-delete','Admin\AdminDotController@deleteDot');
	/* delete belief */
	Route::post('dot-belief-delete','Admin\AdminDotController@deleteBelief');
	/*UPDATE belief*/
	Route::post('dot-belief-update','Admin\AdminDotController@updateDotBeliefDetail')->name('dot-belief-update');
	/*ADD belief in edit section*/
	Route::post('dot-add-belief','Admin\AdminDotController@addBelief')->name('dot-add-belief');
	/*show add page of custom adding page*/
	Route::get('custome-value','Admin\AdminDotController@createCustomValues')->name('custome-value');
	/*store custom value*/
	Route::post('store-custom-value','Admin\AdminDotController@storeCustomValues')->name('store-custom-value');
	/*get custom values list*/
	Route::get('dot-custom-values','Admin\AdminDotController@beliefCustomeValues')->name('dot-custom-values');
	/*edit custom DOT value*/
	Route::get('edit-custom-value/{id}','Admin\AdminDotController@editCustomValue')->name('edit-custom-value');
	/*update dot custom values*/
	Route::post('update-custom-value','Admin\AdminDotController@updateCustomValues')->name('update-custom-value');
	/*delet dot custom values*/
	Route::get('delete-custom-value/{id}','Admin\AdminDotController@deleteCustomValue')->name('delete-custom-value');
	/*get evidence list*/ 
	Route::get('get-evidence-list/{dotId}/{type}/{id}','Admin\AdminDotController@getEvidenceList')->name('get-evidence-list');
	/*get custom dot values modal */
	Route::post('get-custom-value-evidence-modal','Admin\AdminDotController@getDotCustomValueList')->name('get-custom-value-evidence-modal');




	/*USER FUNCTIONALITY*/

	Route::resource('admin-user','Admin\AdminUserController');	

	Route::get('add-staff/{id}','Admin\AdminUserController@addStaff');
	/*get user /staff list*/
	Route::get('view-staff/{id}','Admin\AdminUserController@viewStaffList');
	/*add user by csv file*/
	Route::post('add-user-csv','Admin\AdminUserController@addUserCSV')->name('add-user-csv');
	/*export user list csv*/
	Route::get('user-list-export/{id}','Admin\AdminUserController@exportUserList');
	// delete user
	Route::post('delete-user','Admin\AdminUserController@destroy');


	/*ORGANISATION FUNCTIONALITY*/

	/*get organisation detail DOT COT org. SOT etc*/
	Route::get('organisation-detail/{id}','Admin\AdminOrganisationController@showOrganisationDetail');	
	/*get department create page */
	Route::get('add-office/{id}','Admin\AdminOrganisationController@addOffice');

	Route::get('list-office/{id}','Admin\AdminOrganisationController@listOffice');
	
	Route::post('create-office','Admin\AdminOrganisationController@createOffice');

	/*DEPARTMENT FUNCTIONALITY*/

	/*get all departments list*/
	Route::resource('departments','Admin\AdminDepartmentController');
	
	
	/*ACTION FUNCTIONALITY*/

	/*Dot action lits*/
	Route::get('action-list/{id}/{index?}/{feedthemeId?}','Admin\AdminActionController@getActionList');
	// Route::get('action-list/{id}','Admin\AdminActionController@getActionList');
	/*add DOT action */
	Route::get('add-action/{id}','Admin\AdminActionController@addAction');
	/*store active detail*/
	Route::resource('action','Admin\AdminActionController');
	/*get actions comments*/
	Route::get('action-comments/{id}','Admin\AdminActionController@getCommentsList');
	/*add new comments*/
	Route::post('action-add-comment','Admin\AdminActionController@addComment');
	/*updated actione status*/
	Route::post('action-status-update','Admin\AdminActionController@updateActionStatus');
	/*get responsible user list*/
	Route::POST('get-responsible-users','Admin\AdminActionController@getResUser');
	/*delete action*/
	Route::get('delete-action/{id}','Admin\AdminActionController@deleteAction');
	/*get action theme modal response */
	Route::post('get-action-theme-modal','Admin\AdminActionController@getActionThemeModal')->name('get-action-theme-modal');
	/*add new action theme by ajax when modal is open*/
	Route::post('add-new-action-theme-by-ajax','Admin\AdminActionController@addNewActionThemeByAjax')->name('add-new-action-theme-by-ajax');

	

	/*COMMON FUNCTIONALITY*/

	/*DEPARTMENT functionality*/
	Route::post('admin-add-department','Admin\CommonController@addNewDepartment')->name('admin-add-department');
	/*Common controller*/
	Route::get('get-department','Admin\CommonController@getAllDepartments');	
	/*get dot custom values list*/
	Route::get('get-custom-dot-list','Admin\CommonController@getCustomDotValues');
	/*check email is exists in table*/
	Route::post('search-email','Admin\CommonController@getEmail');	
	/*get offices list*/
	Route::post('get-offices','Admin\CommonController@getOfficeList');
	/*get departments list*/
	Route::post('get-department','Admin\CommonController@getDepartmentList');
	/*get user list*/
	Route::post('get-users','Admin\CommonController@getUsers');

	Route::get('inArray','Admin\CommonController@inArray');
	/*get org name*/
	Route::post('get-org-name','Admin\CommonController@getOrgName')->name('get-org-name');
	/*get search data of the values */
	Route::get('search-dot-values','Admin\CommonController@getDotValueSearchData')->name('search-dot-values');
	// /*send notification mail */
	Route::get('sendNotificationMail','Admin\CommonController@sendNotificationMail')->name('sendNotificationMail');
	/*get offices by organisation*/
	Route::post('getOfficesByOrgId','Admin\CommonController@getOfficesByOrgId');	
	/*get departments by office*/
	Route::post('getDepartmentByOfficecId','Admin\CommonController@getDepartmentByOfficecId');
	/*search organisation functionality in list organisation*/
	Route::post('searchOrganisations','Admin\CommonController@searchOrganisations');
	/*get office search result list*/
	Route::post('searchOffice','Admin\CommonController@searchOffice');
	/*get office search result list*/
	Route::post('searchStaff','Admin\CommonController@searchStaff');
	/*get departments search result list*/
	Route::post('searchDepartment','Admin\CommonController@searchDepartment'); 
	/*get search reports organisation result list*/
	Route::post('searchReportOrganisations','Admin\CommonController@searchReportOrganisations');
	/*get department by office id this is used in report graph section*/
	Route::post('getDepartmentByOfficecIdforGraph','Admin\CommonController@getDepartmentByOfficecIdforGraph');
	/*get office by organisation id this is used in dashboard graph section*/
	Route::post('getOfficeByOrgIdforGraph','Admin\CommonController@getOfficeByOrgIdforGraph');
	/*get department by office id in kudos leaderboard*/
	Route::post('getDepartmentByOfficecIdforKudos','Admin\CommonController@getDepartmentByOfficecIdforKudos');
	/*get office by organisation id in kudos leaderboard*/
	Route::post('getOfficeByOrgIdforKudos','Admin\CommonController@getOfficeByOrgIdforKudos');


	/*COT QUESTIONS FUNCTIONALITY*/

	Route::resource('cot-question','Admin\AdminCOTquestionController');
	/*get functional lens question list*/
	Route::get('cot-fun-questions','Admin\AdminCOTquestionController@getCOTfunctionalLensQuestionList');
	/*get cot functional lens questions option list*/
	Route::get('cot-fun-que-option/{id}','Admin\AdminCOTquestionController@getCOTfunctionalLensQuestionOptionList');
	/*update functional lens question and option*/
	Route::post('update-cot-fun-que-opt','Admin\AdminCOTquestionController@updateFunctionalLensQueOpt');


	
	/*COT FUNCTIONALITY*/

	Route::resource('cot','Admin\AdminCOTController');

	/*get cot detail page*/
	Route::get('cot-detail/{id}','Admin\AdminCOTController@getCotDetail');

	/*get team role map view*/
	Route::match(['get', 'post'],'cot-team-role-map/{id}','Admin\AdminCOTController@getTeamRoleMap');
	/*update organisaton has_cot status*/
	Route::get('cot-team-role-map-update-has-cot/{id}','Admin\AdminCOTController@updateCOTstatus');
	/*get COt maper rank DATA FROM API*/
	Route::get('getCOTmaperkey','API\ApiCOTController@getCOTmaperkey');
	/*get list of functional lens list*/
	Route::match(['get', 'post'],'cot-functional-lens/{id}','Admin\AdminCOTController@getFunctinalLensList');
	/*get functional lens manage page */
	Route::get('manual-functional-lens-detail','Admin\AdminCOTController@manageFunctionalLensList');
	/*update cot functional initial values*/
	Route::post('update-cot-fun-initial-value','Admin\AdminCOTController@updateCOTinitiatialValue');
	/*update cot functional insight values*/
	Route::post('update-cot-fun-strength-value','Admin\AdminCOTController@updateCOTfunctionalLensInsightForStrenghtValue');
	//edit page of COT functional lens tribe tips seek and persuade values
	Route::get('edit-cot-fun-tribe-tips-value/{id}/{type}','Admin\AdminCOTController@editCOTfunTribeTipsSeekPersuadeValues');
	/*update cot functional lens tribe tips seek and persuade values*/
	Route::post('update-cot-fun-tribe-tips-value','Admin\AdminCOTController@updateCOTtribeSeekPersuadevalues');
	/*delete cot functional lense tribe tips value */
	Route::get('delete-cot-fun-tribe-tips-value/{id}','Admin\AdminCOTController@deleteCOTfunLensTribeTipsvalue');
	/*update cot functional lens starting date*/
	Route::post('updateCOTfuncLensStartingDate','Admin\AdminCOTController@updateCOTfuncLensStartingDate');
	/*update cot functional lens tribe tips summay*/
	Route::post('update-cot-tribe-tips-summary','Admin\AdminCOTController@updateTribeTipsSummary');
	/*get COT team role map description list*/

tribe365_live_web/resources/views/admin/actions/actionList.blade.php
<!-- header -->
@section('title', 'List Action')
@include('layouts.adminHeader')

<main class="main-content">
	<div class="add-fild-section organization-fild view-action">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="search-section">						
						<select id="tier-filter" name="tier-filter" class="form-control" onchange="filter_tier();" style="width: 20%; float: right;background:url({{asset('public/images/down-arrow.png')}})no-repeat 95% center;">
							<option value="">Select All Tiers</option>
							<option value="Primary">Primary</option>
							<option value="Secondary">Secondary</option>
							<option value="Tertiary">Tertiary</option>
							<option value="Office">Office</option>
							<option value="Department">Department</option>
							<option value="Individual">Individual</option>	
						</select>
						<div align="center">                            
							@if(session('message'))
							<div class="alert alert-success" role="alert">
								{{session('message')}}
							</div>
							@endif
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="organization-section">
					@php $count=1; @endphp
					@foreach($actions as $action)			

					<div class="col-md-4 {{$action->tier}} alltier">
						<div class="company-section">
							
							<strong class="id-text">{{$action->id}}</strong>
							
							<div class="view-user">								
								<h2>
									@php 
									if(!empty($action->office) && $action->responsibleId==4)
									{
										echo $action->office;
									}
									else if(!empty($action->department) && $action->responsibleId==5)
									{
										echo $action->department;
									}
									else
									{
										echo $action->cname." ".$action->clastName;
									}
									@endphp
								</h2>

							</div>
							<div class="cmt-box">								
								<span class="date"><a href="{{URL::to('admin/action-comments')}}/{{base64_encode($action->id)}}"><img src="{{asset('public/images/comment.png')}}"></a></span>			
							</div>
							<div class="info-icon">
								<a href="{!!route('action.edit',['id'=>base64_encode($action->id)])!!}"><i data-toggle="modal" data-toggle="tooltip" title="Edit" class="fa fa-edit" style="font-size:22px;color:red"></i></a>
							</div>

							<div class="delete-icon">
								<a onclick="return confirm('Are you sure you want to delete ?')" href="{{URL::to('admin/delete-action/'.base64_encode($action->id))}}"><i data-toggle="modal" data-toggle="tooltip" title="Delete" class="fa fa-trash" style="font-size:22px;color:red"></i></a>
							</div>
							
							<div class="comments-text">
								<div class="toltip-section">
									<span class="hide-text">{{ucfirst($action->description)}}</span>
									<div class="toltip-box">{{ucfirst($action->description)}}</div>
								</div>
							</div>
							<div class="status-box">
								<div class="date-box">
									<span class="date-tital"> Start Date : </span>
									<span class="date"> {{date('d-m-Y', strtotime($action->startedDate))}} </span>
								</div>
								<div class="date-box">
									<span class="date-tital"> Due Date : </span>
									<span class="date"> {{date('d-m-Y', strtotime($action->dueDate))}} </span>
								</div>

								<div class="date-box">
									<span class="status-tital"> Status : </span>
									<input id="actionId{{$count}}" type="hidden" name="actionId" value="{{$action->id}}">
									@if(Auth::user()->id==$action->userId)
									<select class="form-control" id="status{{$count}}" name="status" style="margin-left:54px;width:179px;background:url({{asset('public/images/down-arrow.png')}})no-repeat 95% center;">
										<option class="view-status not-started" {{($action->orgStatus=='Not Started')?'selected':''}} value="Not Started" >Not Started</option>
										<option class="view-status started" {{($action->orgStatus=='Started')?'selected':''}} value="Started" >Started</option>
										<option class="view-status complete" {{($action->orgStatus=='Completed')?'selected':''}} value="Completed" >Completed</option>
									</select>
									@else

									@if($action->orgStatus=='Not Started')
									<div class="view-status not-started">
										Not Started
									</div>

									@elseif($action->orgStatus=='Started')
									<div class="view-status started">
										Started
									</div>
									@elseif($action->orgStatus=='Completed')
									<div class="view-status complete">
										Complete
									</div>
									@endif
									@endif
								</div>								
								<div class="date-box">
									<span class="date-tital"> Responsible : </span>
									<span class="date">{{ucfirst($action->rname)." ".ucfirst($action->rlastName)}}  </span>
								</div>
								<div class="date-box">
									<span class="date-tital"> Risks : </span>
									<span class="date">{{$action->themeTitle}}</span>
								</div>
								<div class="date-box">
									<span class="date-tital"> Submissions : </span>
									<span class="date">{{$action->feedbackTitle}}</span>
								</div>
								<!-- <div class="date-box">
									<span class="date-tital"> Risks : </span>
									<div class="toltip-section">
										<span class="hide-text"> {{$action->themeTitle}}</span>
										<div class="toltip-box"> {{$action->themeTitle}}</div>
									</div>
								</div> -->
								<!-- <div class="date-box">
									<span class="date-tital"> Submissions : </span>
									<div class="toltip-section">
										<span class="hide-text"> {{$action->feedbackTitle}}</span>
										<div class="toltip-box"> {{$action->feedbackTitle}}</div>
									</div>
								</div> -->

							</div>
						</div>
					</div>	

					@php $count++ @endphp
					@endforeach	

				</div>
				<div id="resp" align="center" style="width:100%" class="text-danger" role="alert"></div>
			</div>
		</div>

		
	</div>

	<div class="add-plus-icon" style="    position: fixed;">
		<div class="add-plus-upper">
			<a href="{{URL::to('admin/add-action').'/'.$id}}"><img src="{{asset('public/images/plus-icon.png')}}">
			</a>						
		</div>
	</div>
</main>
@include('layouts.adminFooter')

@php $count=1; @endphp
@foreach($actions as $value)

<script type="text/javascript">
	$('#status{{$count}}').on('change', function() {

		var status   = $('#status{{$count}}').val();
		var actionId = $('#actionId{{$count}}').val();

		$.ajax({
			type: "POST",
			url: "{!!URL::to('admin/action-status-update')!!}",				
			data: {status:status,actionId:actionId,"_token":'<?php echo csrf_token()?>'},
			success: function(response) 
			{
				location.reload();
				console.log(response);
			}
		});
	});

	function filter_tier()
	{
		var val   = $('#tier-filter').val();
		$('#resp').html('')

		if(val == "")
		{
			$('.alltier').show();
		}
		else
		{						
			var hasClass = $('.'+val).hasClass(val).toString();

			if(hasClass=='false')
			{
				$('#resp').html('No result found.');
				$('.alltier').hide();
			}
			else
			{				
				$('.alltier').hide();
				$('.'+val).show();
			}
		}
	}
</script>

@php $count++ ;@endphp
@endforeach

tribe365_live_web/resources/views/admin/actions/addAction.blade.php
<!-- header -->
@section('title', 'Add Action')
@include('layouts.adminHeader')
<main class="main-content">
	<div class="add-fild-section">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="fild-stats-cont contact-cont dot-action">
						<h2> Add Action </h2>
						<div class="add-content">
							
							<form id="form" action="{{route('action.store')}}" method="post">
								{{csrf_field()}}

								<input type="hidden" name="orgId" value="{{$id}}">
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<select id="responsible" name="responiblityValue" class="form-control" required>
												<option value="" disabled="" selected="">Action Tier</option>
												@foreach($actionResponsibles as $value)
												<option value="{{$value->id}}">{{$value->name}}</option>
												@endforeach
											</select>
											<span class="select-arrow"><img src="{{asset('public/images/select-arrow.png')}}"></span>
										</div>
									</div>

									<div class="col-md-6">
										<div class="form-group">
											<select id="status" name="status" type="" class="form-control required">
												<option value="" disabled="" selected="">Status</option>
												<option value="Not Started">Not Started</option>
												<option value="Started">Started</option>
												<option value="Completed">Completed</option>
											</select>
											<span class="select-arrow"><img src="{{asset('public/images/select-arrow.png')}}"></span>
										</div>
									</div>

									<div class="col-md-6">
										<div class="form-group">
											<input id="start_date" name="start_date" type="text" class="form-control" placeholder="Start Date" readonly="">
										</div>
									</div>

									<div class="col-md-6">
										<div class="form-group">
											<input id="end_date" name="end_date" type="text" class="form-control" placeholder="Due Date" readonly="">
										</div>
									</div>

									<div class="col-md-6">
										<div class="form-group">
											<div class="select-mnth">						
												<select id="theme" name="themeId[]" multiple="multiple">							
													@foreach($themeList as $themes)
													<option value="{{$themes->id}}">{{ucfirst($themes->title)}}</option>
													@endforeach()
												</select>							
											</div>													
											<input type="hidden" name="themeUpdate" value="1">	
											<form id="new-theme-form">				
												<div id="new-theme-input" style="display: none;">
													<input type="text" id="theme-title" name="theme_title"> 	
													<button id="add-new-theme" type="button"> Add </button>
												</div>
											</form>

										</div>
									</div>

									<div class="col-md-6 resUsers" >
										<div class="form-group">
											<select id="resUsers" name="resUsers" class="form-control" required>
												<option value="" disabled="" selected>Responsible Person</option>
												@foreach($resUsers as $rValue)
												<option value="{{$rValue->id}}">{{ucfirst($rValue->name)." ".ucfirst($rValue->lastName)}}</option>
												@endforeach
											</select>
											<span class="select-arrow"><img src="{{asset('public/images/select-arrow.png')}}"></span>
										</div>
									</div>

									<div class="col-md-6 add-ofc-here"></div>
									<div class="col-md-6 new-resUsers"></div>

									<div class="col-md-6">
										<div class="form-group">
											<div class="select-mnth">						
												<select id="feedback" name="feedbackId[]" multiple="multiple">							
													@foreach($feedbackList as $feedbacks)
													<option value="{{$feedbacks->id}}">{{$feedbacks->id}}</option>
													@endforeach()
												</select>							
											</div>													
										</div>
									</div>
									
									<div class="form-group description">
										<textarea id="description" placeholder="Description" name="description" class="form-control"></textarea>
									</div>
								</div>

								<div id="modal-data"></div>
								
								<button type="button" onclick="validation();" class="btn"> Submit </button>
							</form>

						</div>
					</div>
				</div>
			</div>				
		</div>
	</div>
	<!-- <div class="error-message" style="display: none;">
		<span id="resp"></span>
	</div> -->
	<div class="error-message success" style="display: none;">
		<span id="resp"></span>
	</div>
</main>
@include('layouts.adminFooter')

<script type="text/javascript">
	$(function () {
		$('#theme').multiselect({
			includeSelectAllOption: true,
			enableFiltering:false,
			nonSelectedText: 'Select risks',
		});	
		$('#feedback').multiselect({
			includeSelectAllOption: true,
			enableFiltering:false,
			nonSelectedText: 'Select submissions',
		});			
	});
</script>

<!-- add new theme by ajax when modal is open -->
<script type="text/javascript">
	$('#add-new-theme-show').on('click',function(){
		$('#new-theme-input').show();
	});
</script>

<script type="text/javascript">
	$('#add-new-theme').on('click',function(){
		
		var orgId      = "{{base64_decode($id)}}";
		var themeTitle = $('#theme-title').val();

		$('#theme').html(" ");

		$('#theme').multiselect('refresh');			
		$('.multiselect-selected-text').html('Select theme');

		$.ajax({
			type: "POST",
			url: "{{route('add-new-action-theme-by-ajax')}}",
			data: {orgId:orgId,themeTitle:themeTitle,"_token":'<?php echo csrf_token()?>'},
			success: function(response)
			{
				var obj           = JSON.parse(response);
				var htmlContainer = obj.htmlContainer;
				var htmlOption    = obj.htmlOption
				
				$('#new-theme-input').hide();
				$('#theme').html('');
				$('.multiselect-container').html('');
				$('#theme').append(htmlOption);
				$('.multiselect-container').append(htmlContainer);			
			}
		});
	});
</script>

<!-- modal button  -->
<button style="display: none;" type="button" class="modal-btn" data-toggle="modal" data-target="#myModal"></button>
<!-- modal data appended here -->
<!-- <div id="modal-data"></div> -->

<script type="text/javascript">
	$(document).ready(function(){
		$('.create-btn').click(function(){     
			$('#modal-data').html('');    
			var orgId = $(this).data('id');			
			$('#orgId').val(orgId);

			$.ajax({
				type: "POST",
				url: "{{route('get-action-theme-modal')}}",
				data: {orgId:orgId,"_token":'<?php echo csrf_token()?>'},
				success: function(response)
				{
					console.log(response)
					$('#modal-data').append(response);
					$('.modal-btn').click();
				}
			});
		});
	});
</script>

<script type="text/javascript">
	$(function () {
		$("#start_date").datepicker({

			onSelect: function (selected) {
				var dt = new Date(selected);
				dt.setDate(dt.getDate());
				$("#end_date").datepicker("option", "minDate", dt);
			}
		});

		$("#end_date").datepicker({			
			
			onSelect: function (selected) {
				var dt = new Date(selected);
				dt.setDate(dt.getDate());
				$("#start_date").datepicker("option", "maxDate", dt);
			}
		});
	});
</script>

<script type="text/javascript">
	function validation()
	{
		$('.error-message').show();

		var responsible  = $('#responsible').val();
		var start_date   = $('#start_date').val();
		var end_date     = $('#end_date').val();				
		var description  = $('#description').val();
		var status       = $('#status').val();
		var resUsers     = $('#resUsers').val();
		console.log(responsible);
		
		if (responsible=='' || responsible==null) {

			$('#resp').html();
			$('#resp').html('Please select Action Tier.');
		}
		else if(status=='' || status==null)
		{
			$('#resp').html();
			$('#resp').html('Please select Action Status.');
		}
		else if(start_date =="" || status==null)
		{
			$('#resp').html();
			$('#resp').html('Please select Start Date.');
		}
		else if(end_date =="" || end_date==null)
		{
			$('#resp').html();
			$('#resp').html('Please select End Date.');
		}
		else if(!resUsers || resUsers==null)
		{
			$('#resp').html();
			$('#resp').html('Please select Responsible Person.');
		} 		
		else if(description =="" || description==null)
		{
			$('#resp').html();
			$('#resp').html('Please enter Description.');
		} 		
		else
		{
			$('.error-message').hide();
			$('#form').submit();
		}
	}
</script>

<script type="text/javascript">

	$('#responsible').on('change', function() {
		$('#remove').remove();
		$('#remove1').remove();
		var tierId = $('#responsible').val();
		$('.resUsers').remove();
		$('.add-ofc-here').show();

		if(tierId == 4)
		{			
			var urlTag ="{!!URL::to('admin/get-offices')!!}";
		}
		else if(tierId==5)
		{			
			var urlTag ="{!!URL::to('admin/get-department')!!}";
		}
		// else if(tierId==6)
		// {
			
		// 	var urlTag ="{!!URL::to('admin/get-users')!!}";
		// }
		else if(tierId==1 || tierId==2 || tierId==3 || tierId==6)
		{
			$('.add-ofc-here').hide();
			var urlTag ="{!!URL::to('admin/get-users')!!}";

			$.ajax({
				type: "POST",
				url: "{!!URL::to('admin/get-responsible-users')!!}",				
				data: {section:'',id:'',orgId:'<?php echo $id ?>',"_token":'<?php echo csrf_token()?>'},
				success: function(response) {
				// console.log(response);
				
				$('.new-resUsers').append('<div id="remove1" class="form-group">'+response+'<span class="select-arrow"><img src="{{asset("public/images/select-arrow.png")}}"></span></div>');
			}
		});
			return false;
		}
		
		$.ajax({
			type: "POST",
			url: urlTag,				
			data: {orgId:'<?php echo $id ?>',"_token":'<?php echo csrf_token()?>'},
			success: function(response) {
				// console.log(response);
				
				$('.add-ofc-here').append('<div id="remove" class="form-group">'+response+'<span class="select-arrow"><img src="{{asset("public/images/select-arrow.png")}}"></span></div>');
			}
		});

	});


	$('#form').on('change','#office', function() {
		$('#remove1').remove();
		var officeId = $('#office').val();
		
		$.ajax({
			type: "POST",
			url: "{!!URL::to('admin/get-responsible-users')!!}",				
			data: {section:'office',id:officeId,orgId:'<?php echo $id ?>',"_token":'<?php echo csrf_token()?>'},
			success: function(response) 
			{								
				$('.new-resUsers').append('<div id="remove1" class="form-group">'+response+'<span class="select-arrow"><img src="{{asset("public/images/select-arrow.png")}}"></span></div>');
			}
		});

	});

	$('#form').on('change','#department', function() {
		$('#remove1').remove();
		var departmentId = $('#department').val();
		
		$.ajax({
			type: "POST",
			url: "{!!URL::to('admin/get-responsible-users')!!}",				
			data: {section:'department',id:departmentId,orgId:'<?php echo $id ?>',"_token":'<?php echo csrf_token()?>'},
			success: function(response) 
			{
				$('.new-resUsers').append('<div id="remove1" class="form-group">'+response+'<span class="select-arrow"><img src="{{asset("public/images/select-arrow.png")}}"></span></div>');
			}
		});
	});
</script>